name: ' '
favicon: null
layout_spectrum: 0.26046
typography_spectrum: 0.94702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131313'
    - '#3f3f3f'
    - '#767676'
    - '#8f8f8f'
    - '#cacaca'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
