name: ' '
favicon: null
layout_spectrum: 0.6864482841920108
typography_spectrum: 0.692502387566492
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7767724483273923
  lightness: 0.24392028921283782
  saturation: 0.9424390515778214
  rhythmicContrast: 0.05455589713528752
purpose: []
